<?php $user = Session::get('user'); ?><!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    
    <title><?= strip_tags($this->title) ?> | <?= Request::hostName() ?></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="<?= Url::cdn('css/bootstrap.min.css') ?>">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
    
    <?php foreach (\BootstrapUI::getDependencyCss() as $link) : ?>
    <link rel="stylesheet" href="<?= Url::cdn($link) ?>">
    <?php endforeach; ?>
    
    <script type="text/javascript" src="<?= Url::cdn('js/jquery-2.0.3.min.js') ?>"></script>
  </head>
  <body data-loader="<?= Url::cdn('img/ajax-loader.gif') ?>">
    <!--[if lt IE 7]>
      <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
    <![endif]-->
    
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="<?= Url::href('dashboard') ?>">Crash Analytics</a>
		</div>
  
    	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li<?= (Url::controller() == 'dashboard') ? ' class="active"' : '' ?>><a href="<?= Url::href('dashboard') ?>">Dashboard</a></li>
				<li<?= (Url::controller() == 'live-feed') ? ' class="active"' : '' ?>><a href="<?= Url::href('live-feed') ?>">Live Feed</a></li>
				
				<?php $notifications = isset($user['stats']) ? array_sum(array_values($user['stats'])) : 0; ?>
				<li class="dropdown<?= (Url::controller() == 'reports') ? ' active' : '' ?>">
					<a href="<?= Url::href('reports') ?>" class="dropdown-toggle" data-toggle="dropdown">Reports <?= ($notifications > 0) ? \Bootstrap::label($notifications)->color('red') : '' ?><b class="caret"></b></a>
					<ul class="dropdown-menu">
						<?php foreach (\Menu::getReportLinks() as $url => $text) : ?>
						<li><a href="<?= $url ?>"><?= $text ?></a></li>
						<?php endforeach; ?>
						<li class="divider"></li>
						<li><a href="<?= Url::href('reports') ?>">Search for crash reports</a></li>
					</ul>
				</li>
				<?php if ($user['account_type'] == 'admin') : ?>
				<li class="dropdown<?= (Url::controller() == 'system') ? ' active' : '' ?>">
					<a href="<?= Url::href('calculation') ?>" class="dropdown-toggle" data-toggle="dropdown">System <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><a href="<?= Url::href('system', 'calculation') ?>">Calculation</a></li>
						<li><a href="<?= Url::href('system', 'alerts') ?>">E-mail alerts</a></li>
						<li><a href="<?= Url::href('system', 'users') ?>">Users</a></li>
					</ul>
				</li>
				<?php endif; ?>
				<li<?= (Url::controller() == 'profile') ? ' class="active"' : '' ?>><a href="<?= Url::href('profile') ?>">My profile</a></li>
			</ul>
			
			<ul class="nav navbar-nav navbar-right">
    			<li>
					<p class="navbar-text" style="margin-left: 15px;">
			    		Signed in as <a href="<?= Url::href('profile') ?>" class="navbar-link"><?= $user['username'] ?></a>
			    		<a href="<?= Url::href('index', 'logout') ?>" class="btn btn-danger btn-xs" style="margin-right: 5px;"><span class="glyphicon glyphicon-off"></span></a>
			    	</p>
				</li>
			</ul>
		</div>
    </nav>
    
    <div class="container" style="margin-top: 65px">
	    <?php if (property_exists($this, 'page')) : ?>
	    	<?= $this->render($this->page) ?>
	    <?php elseif (property_exists($this, 'content')) : ?>
	    	<?= is_array($this->content) ? implode("\n", $this->content) : $this->content; ?>
	    <?php endif; ?>
	    
    	<hr/>
	    <footer class="text-center" style="line-height: 50px;">
	    	<a href="https://github.com/vkoudela/Crash-Analytics" target="_blank">Crash Analytics</a>
	    	is developed by <a href="http://vlatko.koudela.org" target="_blank">Vlatko Koudela</a>.
	    </footer>
    </div>
    
    <?php foreach (\Bootstrap::getDependencyJavascript() as $src) : ?>
    <script type="text/javascript" src="<?= Url::cdn($src) ?>"></script>
    <?php endforeach; ?>
    
    <?php foreach (\BootstrapUI::getDependencyJavascript() as $link) : ?>
    <script type="text/javascript" src="<?= Url::cdn($link) ?>"></script>
    <?php endforeach; ?>
    
    <script src="http://code.highcharts.com/highcharts.js"></script>
	<script src="http://code.highcharts.com/modules/exporting.js"></script>
    
  </body>
</html>