<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    
    <title>Login | <?= Request::hostName() ?></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="dns-prefetch" href="//code.highcharts.com">
    
    <?php foreach (\Bootstrap::getDependencyCss() as $link) : ?>
    <link rel="stylesheet" href="<?= Url::cdn($link) ?>">
    <?php endforeach; ?>
    
    <?php foreach (\BootstrapUI::getDependencyCss() as $link) : ?>
    <link rel="stylesheet" href="<?= Url::cdn($link) ?>">
    <?php endforeach; ?>
    
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body data-loader="<?= Url::cdn('img/ajax-loader.gif') ?>">
    <!--[if lt IE 7]>
      <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
    <![endif]-->
    
    <?= $this->loginForm ?>    
    
    <script type="text/javascript" src="<?= Url::cdn('js/jquery-2.0.3.min.js') ?>"></script>
    
    <?php foreach (\Bootstrap::getDependencyJavascript() as $src) : ?>
    <script type="text/javascript" src="<?= Url::cdn($src) ?>"></script>
    <?php endforeach; ?>
    
    <?php foreach (\BootstrapUI::getDependencyJavascript() as $src) : ?>
    <script type="text/javascript" src="<?= Url::cdn($src) ?>"></script>
    <?php endforeach; ?>
  </body>
</html>